map/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thing', views.thing, name='thing')
]

thanks/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('map.urls', namespace='map')),
    url(r'^admin/', include(admin.site.urls)),
]

map/models.py
from django.db import models
from django.utils import timezone

class Thing(models.Model):
    description = models.CharField(max_length=160)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    creation_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.description

map/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.gis.geoip import GeoIP

from .models import Thing
from . import GeocodeService

def index(request):
    latitude, longitude = GeocodeService.get_lat_lon(get_client_ip(request))
    things = Thing.objects.all().order_by('-creation_time')[:100]

    return render(request, 'map/index.html', {
        'center_lat': latitude,
        'center_lon': longitude,
        'things': things,
    })

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

@csrf_exempt
@require_POST
def thing(request):
    lat = request.POST['latitude']
    lon = request.POST['longitude']
    description = request.POST['description']
    thing = Thing(description=description, latitude=lat, longitude=lon)
    thing.save()
    return JsonResponse({'success': True,
        'latitude': lat,
        'longitude': lon,
        'description': description,
    })

map/templates/map/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'map/style.css' %}">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpjO331YDIqYfeXOuKwupE67l1c-PQPJU"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript">
      var map;
      var thankfulwindow;
      var infowindow;
      function initialize() { var mapOptions = {
          center: { lat: {{ center_lat }}, lng: {{ center_lon }} },
          zoom: 5,
          mapTypeControl: true,
          mapTypeControlOptions: {
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
            position: google.maps.ControlPosition.TOP_RIGHT
          },
          panControl: false,
          zoomControl: true,
          zoomControlOptions: {
            style: google.maps.ZoomControlStyle.LARGE,
            position: google.maps.ControlPosition.RIGHT_TOP
          },
          scaleControl: false,
          streetViewControl: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        thankfulwindow = new google.maps.InfoWindow({
          map: map,
          position: { lat: {{ center_lat }}, lng: {{ center_lon }} },
          content: '<h2>What are you thankful for?</h2>' +
              '<form action="#">' +
                '<input type="text" id="id_thankful">' +
                '<button onclick="giveThanks()">&gt;</button>' +
              '</form>'
        });

        google.maps.event.addListener(map, 'center_changed', function() {
            thankfulwindow.setPosition(map.getCenter());
        });

        if(navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

            thankfulwindow.setPosition(pos);
            map.setCenter(pos);
          }, function() {
          });
        }

        var locations = [
        {% for thing in things %}
          ["{{ thing.description|escapejs }}", {{ thing.latitude }}, {{ thing.longitude }}],
        {% endfor %}
        ];

        infowindow = new google.maps.InfoWindow();
        var marker, i;
        for (i = 0; i < locations.length; i++) {
          marker = new google.maps.Marker({
            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
            map: map
          });

          google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
              infowindow.setContent(locations[i][0]);
              infowindow.open(map, marker);
            }
          })(marker, i));
        }
      }

      function giveThanks() {
        var data = {
          'description': $("#id_thankful").val(),
          'latitude': map.getCenter().lat(),
          'longitude': map.getCenter().lng(),
        };
        $.post('{% url 'map:thing' %}', data, function(data) {
            console.log(data);
        });

        thankfulwindow.close();

        var marker = new google.maps.Marker({
          position: new google.maps.LatLng(data['latitude'], data['longitude']),
          map: map,
        });

        infowindow.setContent(data['description']);
        infowindow.open(map, marker);

        google.maps.event.addListener(marker, 'click', function(marker, i) {
          infowindow.setContent(data['description']);
          infowindow.setPosition({'lat': data['latitude'], 'lng': data['longitude']});
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
    <div id="map-canvas"></div>
  </body>
</html>